### ISSUE TITLE
configure issue on newest versions - 32bit

### ISSUE THREAD

**Issue by keleko34** [nwjs/nw-gyp#124]
Running command:
`nw-gyp configure --target=0.34.1 --arch=ia32`

Getting results:
```
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@11.0.0 | win32 | ia32
gyp info spawn C:\Program Files (x86)\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\dev\\NodeAddons\\NTDirect32\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\<user>\\.nw-gyp\\0.34.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\<user>\\.nw-gyp\\0.34.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file="C:\\Users\\<user>\\.nw-gyp\\0.34.1\\<(target_arch)\\node.lib"',
gyp info spawn args   '-Dnw_lib_file="C:\\Users\\<user>\\.nw-gyp\\0.34.1\\<(target_arch)\\nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=D:\\dev\\NodeAddons\\NTDirect32',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\dev\\NodeAddons\\NTDirect32\\build',
gyp info spawn args   '-Goutput_dir=.' ]
C:\Program: can't open file 'Files': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\<user>\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:359:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure" "--target=0.34.1" "--arch=ia32"
gyp ERR! cwd D:\dev\NodeAddons\NTDirect32
gyp ERR! node -v v11.0.0
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok
```

Instructions followed:
1. installed windows-build-tools
2. set npm configs
3. created binding.gyp

Only differences I know of:
I am running visual studio 2017 although I still used the windows build tools so 2015 build tools are installed

Any help figuring out why this error would be showing? I have no way to debug this issue as the information given is very limited on the file it is searching for.

Another note is this module builds and configures just fine using `node-gyp` and `node-pre-gyp` and I only have issues with `nw-gyp` on configuring properly.

**Comment by keleko34** [comment]
After some testing of the library I have discovered the issue... It seams in the nw-gyp file: `/src/configure.js` there is an issue with the `findConfigs` method. a config is created at the directory: `/build/config.gypi` while the path.resolve in this method references only `config.gypi` which resolves to `/config.gypi` not `/build/config.gypi` and then failing the `fs.stat` command...

**Comment by keleko34** [comment]
It also seems the `common.gypi` file is not being created.

**Comment by keleko34** [comment]
to Anybody that may have this issue come up, it was due to python directory having a space in it... I had to move it to `C:/Python27` for it to work properly for `nw-gyp`
