### ISSUE TITLE
Unable to build sqlite3 on archlinux

### ISSUE THREAD

**Issue by diginfo** [nwjs/nw-gyp#126]
These commands have no effect whatsoever under linux:

```
npm config set python /usr/bin/python2
nw-gyp --python /usr/bin/python2
```

Call to 'python -c "import sys; print sys.byteorder"' - npm and  / or nw-gyp are still trying to call python3:

```
# npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.33.0

> sqlite3@4.0.4 install /usr/share/nodejs/nwjs-33-sdk/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
  File "<string>", line 1
    import sys; print sys.byteorder
                        ^
SyntaxError: invalid syntax
gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

**Comment by polhaghverdian** [comment]
I have the same issue on Windows 10, 


>   File "<string>", line 1
>     import sys; print sys.byteorder
>                         ^
> SyntaxError: invalid syntax
> gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Pol\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:359:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Windows_NT 10.0.18362
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pol\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.40.1" "--arch=x64"
> gyp ERR! cwd C:\Users\Pol\Desktop\dev\nwjs-sdk-v0.40.1-win-x64\addon
> gyp ERR! node -v v10.16.3
> gyp ERR! nw-gyp -v v3.6.3
> gyp ERR! not ok
