### ISSUE TITLE
Undefined variable standalone_static_library in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by panther7** [nwjs/nw-gyp#159]
It's broken on NodeJS 19 and newer.

https://github.com/nodejs/node/pull/43627

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/nw-gyp/lib/configure.js:367:16)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.1.0-0.deb11.11-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/nw-gyp" "configure" "--fallback-to-build" "--module=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3
gyp ERR! node -v v20.8.1
gyp ERR! nw-gyp -v v3.6.6
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Linux 6.1.0-0.deb11.11-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3
node-pre-gyp ERR! node -v v20.8.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp configure --fallback-to-build --module=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3/lib/binding/napi-v6-linux-glibc-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! code 1
npm ERR! path /home/gitlab-runner/builds/6ceadb2d/0/sbrowser/software/browser-custom-modules-sources/submodule/sbrowser-sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-24T12_32_53_278Z-debug-0.log
```

**Comment by nodejsdevs** [comment]
Look this https://nodeer.space/questions/building-an-npm-module-specifically-designed-for-ionic-app-development-requires-a-strategic-approach

**Comment by sitnell99** [comment]
this worked for me - https://github.com/nwjs/nw-gyp/issues/155#issuecomment-1308701166
