### ISSUE TITLE
error: redeclaration of ‘<typeprefixerror>__shared__’

### ISSUE THREAD

**Issue by hartsantler** [nwjs/nw-gyp#79]
I have some code that may require c++11, im not really sure why nw-gyp fails to build my code, because when i use the same template functions in my other projects, g++ is able to compile it without any problems.

```
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@0.10.36 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/brett/.nw-gyp/0.12.3/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/brett/.nw-gyp/0.12.3',
gyp info spawn args   '-Dmodule_root_dir=/tmp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '-Dv13=0',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@0.10.36 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/build'
  CXX(target) Release/obj.target/binding/binding.o
../binding.cc: In function ‘void MyMethod(const v8::FunctionCallbackInfo<v8::Value>&)’:
../binding.cc:8:28: error: ‘__shared__’ was not declared in this scope
  __shared__(__shared__(args)->GetReturnValue())->Set(String::NewFromUtf8(isolate, std::string("world")));
                            ^
../binding.cc:8:47: error: ‘__shared__’ was not declared in this scope
  __shared__(__shared__(args)->GetReturnValue())->Set(String::NewFromUtf8(isolate, std::string("world")));
                                               ^
../binding.cc:8:47: error: redeclaration of ‘<typeprefixerror>__shared__’
../binding.cc:8:28: note: previous declaration ‘<typeprefixerror>__shared__’
  __shared__(__shared__(args)->GetReturnValue())->Set(String::NewFromUtf8(isolate, std::string("world")));
                            ^
../binding.cc:8:83: error: ‘string’ is not a member of ‘std’
  __shared__(__shared__(args)->GetReturnValue())->Set(String::NewFromUtf8(isolate, std::string("world")));
                                                                                   ^
../binding.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../binding.cc:12:32: error: ‘string’ is not a member of ‘std’
  NODE_SET_METHOD(target, std::string("hello"), MyMethod);
                                ^
binding.target.mk:90: recipe for target 'Release/obj.target/binding/binding.o' failed
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory '/tmp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/nw-gyp/lib/build.js:286:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.6-200.fc22.x86_64
gyp ERR! command "node" "/usr/bin/nw-gyp" "build"
gyp ERR! cwd /tmp
gyp ERR! node -v v0.10.36
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok 
```
## c++ source

``` c++

#include <memory>
#include <vector>
#include <array>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <map>
#include <algorithm>
#include <functional>
#include <thread>
#include <chrono>
#include <cmath>

typedef long   i64;
typedef int    i32;
typedef double f64;
typedef float  f32;
typedef const char*  cstring;


template<class T>
std::shared_ptr<T> __shared__(T* ob) {return std::make_shared<T>(ob);}

template<class T>
std::shared_ptr<T> __shared__(T& ob) {return std::make_shared<T>(&ob);}

template<class T>
std::shared_ptr<T> __shared__(std::shared_ptr<T> ob) {return ob;}


std::shared_ptr<std::string> __shared__(std::string ob) {
    return std::make_shared<std::string>(ob);
}

std::shared_ptr<std::runtime_error> __shared__(std::runtime_error ob) {
    return std::make_shared<std::runtime_error>(ob);
}



template<class T>
T* __pointer__(T* ob) {return ob;}

template<class T>
T* __pointer__(T& ob) {return &ob;}

template<class T>
T* __pointer__(T ob) {return &ob;}  // compiler optimizes away the copy?

std::string* __pointer__(std::string ob) {
    return &ob;
}

template<class T>
T* __pointer__(std::shared_ptr<T> ob) {return ob.get();}



std::runtime_error* RuntimeError(std::string msg) {

    auto prefix = std::string("RuntimeError|");  /* auto-fallback */
    return new std::runtime_error(prefix+msg);
}
std::runtime_error* IOError(std::string msg) {

    auto prefix = std::string("IOError|");  /* auto-fallback */
    return new std::runtime_error(prefix+msg);
}


const char* cstr( std::string s ) { return s.c_str(); }

std::string __string_upper__( std::string s ) {
    auto a = std::string("");
    for (auto c: s) {
        a += std::toupper(c);
    }
    return a;
}

std::string __string_lower__( std::string s ) {
    auto a = std::string("");
    for (auto c: s) {
        a += std::tolower(c);
    }
    return a;
}

std::shared_ptr<std::vector<std::string>> __split_string__(std::string s, std::string c) {
    auto vec = std::vector<std::string>();
    vec.push_back(std::string(""));
    for (auto i=0; i<s.size()-1; i++) {
        auto v = std::string(&s.at(i));
        v.resize(1);
        if (v == c) {
            vec.push_back(std::string(""));
        } else {
            vec.back() += v;
        }
    }
    return std::make_shared<std::vector<std::string>>(vec);
}

double __double__(int a) { return (double)a; }

int sum(std::shared_ptr<std::vector<int>> arr) {
    int s = 0;
    std::for_each(arr->begin(),arr->end(),[&](int n){s += n;});
    return s;
}
double sumd(std::shared_ptr<std::vector<double>> arr) {
    double s = 0.0;
    std::for_each(arr->begin(),arr->end(),[&](double n){s += n;});
    return s;
}
float sumf(std::shared_ptr<std::vector<float>> arr) {
    float s = 0.0;
    std::for_each(arr->begin(),arr->end(),[&](float n){s += n;});
    return s;
}


std::string str( const std::string s ) {
    return s;
}
std::string str( int s ) {
    return std::to_string(s);
}

std::fstream* __open__(const std::string name, const std::string mode) {
    try {
        std::fstream* s;
        if (mode==std::string("rb") || mode==std::string("r")) {
            s = new std::fstream(name.c_str(), std::fstream::in | std::fstream::binary);
        } else {
            s = new std::fstream(name.c_str(), std::fstream::out | std::fstream::binary);
        }
        s->exceptions( std::ios::failbit | std::ios::badbit | std::ios::eofbit );
        return s;   
    } catch (...) {
        throw IOError(std::string("No such file or directory: ")+name);
    }
}

std::string readfile(std::fstream* f) {
    std::ostringstream c;
    c << f->rdbuf();
    f->close();
    return c.str();
}

std::vector<int> __range1__( int n ) {
    std::vector<int> vec(n);
    for (int i=0; i<n; i++) {
        vec[i] = i;
    }
    return vec;
}


std::shared_ptr<std::vector<int>> range1( int n ) {
    std::vector<int> vec(n);
    for (int i=0; i<n; i++) {
        vec[i] = i;
    }
    return std::make_shared<std::vector<int>>(vec);
}

std::shared_ptr<std::vector<int>> range2( int start, int end ) {
    std::vector<int> vec(end-start);
    int index = 0;
    for (int i=start; i<end; i++) {
        vec[index] = i;
        index ++;
    }
    return std::make_shared<std::vector<int>>(vec);
}

int ord( std::string s) {
    int r = (int)s.c_str()[0];
    return r;
}

double __float__( std::string s ) {
    return std::stod( s );
}

double round( double n, int places ) {
    auto p = std::pow(10, places);
    return std::round(n * p) / p;
}

std::string chr( int c ) {
    auto s = static_cast<char>(c);
    return std::string( &s );
}

std::string __parse_error_type__( std::runtime_error* err) {
    auto vec = __split_string__( std::string(err->what()), std::string("|") );
    return (*vec)[0];
}

/*end-builtins*/
#include "node.h"
#include "v8.h"
using namespace v8;
void MyMethod(const FunctionCallbackInfo<Value>& args) {

    auto isolate = Isolate::GetCurrent();  /* auto-fallback */
    auto scope = HandleScope(isolate);          /* new variable */
    __shared__(args::GetReturnValue())->Set(String::NewFromUtf8(isolate, std::string("world")));
}
void init(Handle<Object> target) {

    NODE_SET_METHOD(target, std::string("hello"), MyMethod);
}
NODE_MODULE(binding, init);
```
## bindings.gyp

```
{
  'targets': [
    {
      'target_name': 'binding',
      'sources': [ 'binding.cc' ]
    }
  ]
}
```

**Comment by ghostoy** [comment]
It should be fixed by our latest release of nw-gyp.
