### ISSUE TITLE
nw-gyp rebuild is taking nodejs version instead nw-gyp version

### ISSUE THREAD

**Issue by carlosdioxinet** [nwjs/nw-gyp#90]
When i tried to rebuild a package, i got this:

```
computer:printer user$ nw-gyp rebuild
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.4.3 | darwin | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v4.4.3/nw-headers-v4.4.3.tar.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v4.4.3/nw-headers-v4.4.3.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/user/.nvm/versions/node/v4.4.3/lib/node_modules/nw-gyp/lib/install.js:236:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/user/.nvm/versions/node/v4.4.3/lib/node_modules/nw-gyp/node_modules/request/request.js:977:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/user/.nvm/versions/node/v4.4.3/bin/node" "/Users/user/.nvm/versions/node/v4.4.3/bin/nw-gyp" "rebuild"
gyp ERR! node -v v4.4.3
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok 
```

Seems that configure task is taking node version instead nw-gyp version.

**Comment by rribou** [comment]
nw-gyp --target=0.15.2 rebuild

Adapt target to your nw.js version.

**Comment by ghostoy** [comment]
nw-gyp is running on Node.js not NW.js. So `--target` is required to specify the version of NW.js.
