### ISSUE TITLE
Unable to update modules for 0.17.0

### ISSUE THREAD

**Issue by uplusion23** [nwjs/nw-gyp#96]
All attempts for any node module leaves me with an error listed below.

```
SyntaxError: EOL while scanning string literal
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\uplusion23\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:324:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\uplusion23\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.17.0"
gyp ERR! cwd C:\Users\uplusion23\Desktop\DIRECTORY\app\node_modules\asynckeystate
gyp ERR! node -v v4.5.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by rogerwang** [comment]
This is fixed now with the new header files.

**Comment by uplusion23** [comment]
A new issue arises after applying the fix.

```
gyp: name 'component' is not defined while evaluating condition 'OS=="win" and component=="shared_library"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\uplusion23\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:324:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\uplusion23\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.17.0"
gyp ERR! cwd C:\Users\uplusion23\Desktop\DIRECTORY\app\node_modules\asynckeystate
gyp ERR! node -v v4.5.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
```

As it seems related, I have chosen to not produce a new issue ticket, but can if needed.

**Comment by ghostoy** [comment]
@uplusion23 Temporarily you can workaround it by setting `GYP_DEFINES` env to `component=static_library` before running `nw-gyp` on Windows. We will fix later.

**Comment by uplusion23** [comment]
@ghostoy Talking about line 7 on common.gpyi? It's set to static_library already.

**Edit** When reading the error, the environment seems to already have it set as default

```
gyp info spawn args   'component=static_library',
```

**Comment by ghostoy** [comment]
@uplusion23 It's set in `common.gypi`, but `gyp` tool won't use variable definitions within the same level.
